### ISSUE TITLE
hypyp.utils.split: channel names in the resulting Raw objects

### ISSUE THREAD

**Issue by alicja444** [ppsp-team/HyPyP#185]
Dear HyPyP Team,

When using the hypyp.utils.split() function to create two separate data objects from a merged object, both resulting Raw objects have the same channel names, corresponding to Subject 1 (e.g., "O1S1"). The data is clearly different when plotted, so I assume it is separated correctly. But the original merged datasets had the S1 suffix for Subject 1 channels, and S2 suffix for Subject 2 channels (e.g. "O1S1" and "O1S2"), so I expected the resulting separate Raw objects to retain these channel names (or get rid of the suffixes altogether). Is what I am describing intended behavior?   

Thank you!
Alicja

**Comment by deep-introspection** [comment]
Greetings,

The hypyp.utils.merge function is adding "_S1" and "_S2" to the channels' names: https://github.com/ppsp-team/HyPyP/blob/9f4769ac37805499bc15d41f9b38e1daaaa36e67/hypyp/utils.py#L138-L143

For hypyp.utils.split, the function expect a similar labelling since it cut the strings at '_' to extract channel names: https://github.com/ppsp-team/HyPyP/blob/9f4769ac37805499bc15d41f9b38e1daaaa36e67/hypyp/utils.py#L220

I hope this helps!
Guillaume
